# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=50)),
                ('media', models.CharField(max_length=50)),
                ('yardline', models.IntegerField()),
                ('quarter', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('down', models.IntegerField()),
                ('togo', models.IntegerField()),
                ('redzone', models.BooleanField()),
                ('clock', models.CharField(max_length=50)),
                ('posteam', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbr', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
                ('score_5', models.IntegerField()),
                ('score_T', models.IntegerField()),
                ('to', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('tkl', models.IntegerField()),
                ('ast', models.IntegerField()),
                ('sk', models.IntegerField()),
                ('int', models.IntegerField()),
                ('ffum', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Fumble',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('tot', models.IntegerField()),
                ('rcv', models.IntegerField()),
                ('trcv', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('lost', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Kicking',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('fgm', models.IntegerField()),
                ('fga', models.IntegerField()),
                ('fgyds', models.IntegerField()),
                ('totpfg', models.IntegerField()),
                ('xpmade', models.IntegerField()),
                ('xpmissed', models.IntegerField()),
                ('xpa', models.IntegerField()),
                ('xpb', models.IntegerField()),
                ('xptot', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='KickRet',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('ret', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('lngtd', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('att', models.IntegerField()),
                ('cmp', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('twopta', models.IntegerField()),
                ('twoptm', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Punting',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('pts', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('i20', models.IntegerField()),
                ('lng', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='PuntRet',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('ret', models.IntegerField()),
                ('avg', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('lngtd', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('rec', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('lngtd', models.IntegerField()),
                ('twopta', models.IntegerField()),
                ('twoptm', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='Rushing',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='turkeybowl.PlayerStat')),
                ('att', models.IntegerField()),
                ('yds', models.IntegerField()),
                ('tds', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('lngtd', models.IntegerField()),
                ('twopta', models.IntegerField()),
                ('twoptm', models.IntegerField()),
            ],
            bases=('turkeybowl.playerstat',),
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='turkeybowl.TeamPerformance')),
                ('totfd', models.IntegerField()),
                ('totyds', models.IntegerField()),
                ('pyds', models.IntegerField()),
                ('ryds', models.IntegerField()),
                ('pen', models.IntegerField()),
                ('penyds', models.IntegerField()),
                ('trnovr', models.IntegerField()),
                ('pt', models.IntegerField()),
                ('ptyds', models.IntegerField()),
                ('ptavg', models.IntegerField()),
                ('top', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='teamperformance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkeybowl.Team'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkeybowl.Game'),
        ),
        migrations.AddField(
            model_name='playerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turkeybowl.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_perf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='turkeybowl.TeamPerformance'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_perf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='turkeybowl.TeamPerformance'),
        ),
    ]
