# Generated by Django 2.2.5 on 2019-09-30 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.IntegerField(default=0)),
                ('away_score', models.IntegerField(default=0)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_stats.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_stats.Player')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_nfl_stats.stat_set+', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbreviation', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='defense', max_length=20)),
                ('tackle', models.IntegerField()),
                ('assisted_tackle', models.IntegerField()),
                ('sack', models.IntegerField()),
                ('interception', models.IntegerField()),
                ('forced_fumble', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Fumble',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='fumble', max_length=20)),
                ('total', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('lost', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Kicking',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='kicking', max_length=20)),
                ('field_goals_made', models.IntegerField()),
                ('field_goal_attempts', models.IntegerField()),
                ('field_goal_yards', models.IntegerField()),
                ('total_field_goal_points', models.IntegerField()),
                ('extra_points_made', models.IntegerField()),
                ('extra_points_missed', models.IntegerField()),
                ('extra_points_attempted', models.IntegerField()),
                ('extra_points_blocked', models.IntegerField()),
                ('extra_points_total', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='KickRet',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='kick_return', max_length=20)),
                ('returns', models.IntegerField()),
                ('average', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='passing', max_length=20)),
                ('attempts', models.IntegerField()),
                ('completions', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Punting',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='punting', max_length=20)),
                ('punts', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('average', models.IntegerField()),
                ('inside_20_yard_line', models.IntegerField()),
                ('longest', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='PuntRet',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='punt_return', max_length=20)),
                ('returns', models.IntegerField()),
                ('average', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='receiving', max_length=20)),
                ('receptions', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.CreateModel(
            name='Rushing',
            fields=[
                ('stat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.Stat')),
                ('stat_type', models.CharField(default='rushing', max_length=20)),
                ('attempts', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('nfl_stats.stat',),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='nfl_stats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='away_team', to='nfl_stats.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='home_team', to='nfl_stats.Team'),
        ),
    ]
