# Generated by Django 2.2.5 on 2019-09-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weather', models.CharField(max_length=50)),
                ('media', models.CharField(max_length=50)),
                ('yardline', models.IntegerField()),
                ('quarter', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=50)),
                ('down', models.IntegerField()),
                ('togo', models.IntegerField()),
                ('redzone', models.BooleanField()),
                ('clock', models.CharField(max_length=50)),
                ('posteam', models.CharField(max_length=50)),
                ('stadium', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_stats.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_stats.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('abbr', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_1', models.IntegerField()),
                ('score_2', models.IntegerField()),
                ('score_3', models.IntegerField()),
                ('score_4', models.IntegerField()),
                ('score_5', models.IntegerField()),
                ('score_T', models.IntegerField()),
                ('to', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nfl_stats.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Defense',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('tackle', models.IntegerField()),
                ('assisted_tackle', models.IntegerField()),
                ('sack', models.IntegerField()),
                ('interception', models.IntegerField()),
                ('forced_fumble', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Fumble',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('total', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('total_recovered', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('lost', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Kicking',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('field_goals_made', models.IntegerField()),
                ('field_goal_attempts', models.IntegerField()),
                ('field_goal_yards', models.IntegerField()),
                ('total_field_goal_points', models.IntegerField()),
                ('extra_points_made', models.IntegerField()),
                ('extra_points_missed', models.IntegerField()),
                ('extra_points_attempted', models.IntegerField()),
                ('extra_points_blocked', models.IntegerField()),
                ('extra_points_total', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='KickRet',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('returns', models.IntegerField()),
                ('average', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Passing',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('attempts', models.IntegerField()),
                ('completions', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('interceptions', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Punting',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('punts', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('average', models.IntegerField()),
                ('inside_20_yard_line', models.IntegerField()),
                ('longest', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='PuntRet',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('returns', models.IntegerField()),
                ('average', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Receiving',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('receptions', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='Rushing',
            fields=[
                ('playerstat_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nfl_stats.PlayerStat')),
                ('attempts', models.IntegerField()),
                ('yards', models.IntegerField()),
                ('touchdowns', models.IntegerField()),
                ('longest', models.IntegerField()),
                ('longest_touchdown', models.IntegerField()),
                ('two_point_attempts', models.IntegerField()),
                ('two_points_made', models.IntegerField()),
            ],
            bases=('nfl_stats.playerstat',),
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nfl_stats.TeamPerformance')),
                ('totfd', models.IntegerField()),
                ('totyds', models.IntegerField()),
                ('pyds', models.IntegerField()),
                ('ryds', models.IntegerField()),
                ('pen', models.IntegerField()),
                ('penyds', models.IntegerField()),
                ('trnovr', models.IntegerField()),
                ('pt', models.IntegerField()),
                ('ptyds', models.IntegerField()),
                ('ptavg', models.IntegerField()),
                ('top', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_perf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='nfl_stats.TeamPerformance'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_perf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='nfl_stats.TeamPerformance'),
        ),
    ]
