# Generated by Django 2.2.5 on 2019-09-30 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_stats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defense',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='fumble',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='kicking',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='kickret',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='passing',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='punting',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='puntret',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='receiving',
            name='stat_type',
        ),
        migrations.RemoveField(
            model_name='rushing',
            name='stat_type',
        ),
        migrations.AddField(
            model_name='stat',
            name='stat_type',
            field=models.CharField(default='generic', max_length=20),
        ),
    ]
