# Generated by Django 2.2.5 on 2019-09-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl_stats', '0002_auto_20190929_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='stat_type',
        ),
        migrations.AddField(
            model_name='defense',
            name='stat_type',
            field=models.CharField(default='defense', max_length=20),
        ),
        migrations.AddField(
            model_name='fumble',
            name='stat_type',
            field=models.CharField(default='fumble', max_length=20),
        ),
        migrations.AddField(
            model_name='kicking',
            name='stat_type',
            field=models.CharField(default='kicking', max_length=20),
        ),
        migrations.AddField(
            model_name='kickret',
            name='stat_type',
            field=models.CharField(default='kick_return', max_length=20),
        ),
        migrations.AddField(
            model_name='passing',
            name='stat_type',
            field=models.CharField(default='passing', max_length=20),
        ),
        migrations.AddField(
            model_name='punting',
            name='stat_type',
            field=models.CharField(default='punting', max_length=20),
        ),
        migrations.AddField(
            model_name='puntret',
            name='stat_type',
            field=models.CharField(default='punt_return', max_length=20),
        ),
        migrations.AddField(
            model_name='receiving',
            name='stat_type',
            field=models.CharField(default='receiving', max_length=20),
        ),
        migrations.AddField(
            model_name='rushing',
            name='stat_type',
            field=models.CharField(default='rushing', max_length=20),
        ),
    ]
